import type { TErrorCodes } from "@/lib/auth-error";

export const ERROR_COPY: Record<TErrorCodes, string> = {
    // Resend email errors
    invalid_idempotency_key: "",
    validation_error: "",
    missing_api_key: "",
    restricted_api_key: "",
    invalid_api_key: "",
    not_found: "",
    method_not_allowed: "",
    invalid_idempotent_request: "",
    concurrent_idempotent_requests: "",
    invalid_attachment: "",
    invalid_from_address: "",
    invalid_access: "",
    invalid_parameter: "",
    invalid_region: "",
    missing_required_field: "",
    monthly_quota_exceeded: "",
    daily_quota_exceeded: "",
    rate_limit_exceeded: "",
    security_error: "",
    application_error: "",
    internal_server_error: "",

    // Internally made errors
    password_mismatch: "Passwords do not match.",
    totp_uri_not_found: "",
    generic_error: "Something wrong happened.",
    otp_failed: "Verification failed.",
    code_invalid: "Invalid verification code.",
    field_missing_code: "Missing OTP",
    field_missing_email: "Missing email",
    field_missing_password: "Missing password",
    field_missing_password_repeat: "Missing password",
    internal_field_missing_oauth: "500",
    oauth_no_url_given_by_provider: "500",
    internal_field_missing_action: "500",
    internal_field_unknown_oauth_provider: "500",

    // Better Auth errors
    ASYNC_VALIDATION_NOT_SUPPORTED: "",
    CALLBACK_URL_REQUIRED: "",
    CROSS_SITE_NAVIGATION_LOGIN_BLOCKED: "",
    EMAIL_ALREADY_VERIFIED: "",
    EMAIL_MISMATCH: "",
    FAILED_TO_CREATE_VERIFICATION: "",
    FIELD_NOT_ALLOWED: "",
    INVALID_CALLBACK_URL: "",
    INVALID_ERROR_CALLBACK_URL: "",
    INVALID_NEW_USER_CALLBACK_URL: "",
    INVALID_ORIGIN: "",
    INVALID_REDIRECT_URL: "",
    LINKED_ACCOUNT_ALREADY_EXISTS: "",
    MISSING_FIELD: "",
    MISSING_OR_NULL_ORIGIN: "",
    SESSION_NOT_FRESH: "",
    VALIDATION_ERROR: "",
    VERIFICATION_EMAIL_NOT_ENABLED: "",
    INVALID_USERNAME: "Username is invalid.",
    USERNAME_IS_TOO_SHORT: "Username is too short.",
    USERNAME_TOO_SHORT: "Username is too short.",
    USERNAME_IS_TOO_LONG: "Username is too long.",
    USERNAME_TOO_LONG: "Username is too long.",
    ACCOUNT_NOT_FOUND: "Invalid credentials.",
    CREDENTIAL_ACCOUNT_NOT_FOUND: "Invalid credentials.",
    INVALID_OTP: "Code is incorrect.",
    USERNAME_IS_ALREADY_TAKEN_PLEASE_TRY_ANOTHER: "Username taken.",
    USER_ALREADY_EXISTS_USE_ANOTHER_EMAIL: "Email taken.",
    INVALID_OTP_CODE: "Code must be 6 digits.",
    TOO_MANY_ATTEMPTS: "Too many unsuccessful attempts.",
    EMAIL_CAN_NOT_BE_UPDATED: "Email cannot be updated.",
    EMAIL_NOT_VERIFIED: "Email is not yet verified.",
    FAILED_TO_CREATE_SESSION: "",
    FAILED_TO_CREATE_USER: "",
    FAILED_TO_GET_SESSION: "",
    FAILED_TO_GET_USER_INFO: "",
    FAILED_TO_UNLINK_LAST_ACCOUNT: "You can't unlink your last account.",
    FAILED_TO_UPDATE_USER: "",
    ID_TOKEN_NOT_SUPPORTED: "",
    INVALID_EMAIL: "Invalid email.",
    INVALID_EMAIL_OR_PASSWORD: "Invalid credentials.",
    // This error is for both if the password on registration does
    // not meet requirements, and in other checks like 2fa-enable where
    // you get the password icorrent.
    INVALID_PASSWORD: "Invalid password.",
    INVALID_TOKEN: "",
    PASSWORD_TOO_LONG: "",
    PASSWORD_TOO_SHORT: "",
    PROVIDER_NOT_FOUND: "",
    SESSION_EXPIRED: "",
    SOCIAL_ACCOUNT_ALREADY_LINKED: "",
    USER_ALREADY_EXISTS: "There is already an account with this email.",
    USER_ALREADY_HAS_PASSWORD: "",
    USER_EMAIL_NOT_FOUND: "",
    USER_NOT_FOUND: "Invalid credentials.",
    USERNAME_IS_ALREADY_TAKEN: "Username is taken.",
    UNABLE_TO_CREATE_SESSION: "",
    AUTHENTICATION_FAILED: "",
    BACKUP_CODES_NOT_ENABLED: "",
    CHALLENGE_NOT_FOUND: "",
    FAILED_TO_UPDATE_PASSKEY: "",
    FAILED_TO_VERIFY_REGISTRATION: "",
    INVALID_BACKUP_CODE: "",
    INVALID_CODE: "Two factor code is invalid.",
    INVALID_DISPLAY_USERNAME: "",
    INVALID_TWO_FACTOR_COOKIE: "Login expired. Log out and log back in again.",
    INVALID_USERNAME_OR_PASSWORD: "Invalid credentials.",
    OTP_EXPIRED: "",
    OTP_HAS_EXPIRED: "OTP has expired.",
    OTP_NOT_ENABLED: "",
    PASSKEY_NOT_FOUND: "",
    TOO_MANY_ATTEMPTS_REQUEST_NEW_CODE: "",
    TOTP_NOT_ENABLED: "",
    TWO_FACTOR_NOT_ENABLED: "",
    UNEXPECTED_ERROR: "",
    YOU_ARE_NOT_ALLOWED_TO_REGISTER_THIS_PASSKEY: "",
};

type RouteKey = "default" | "home" | "login" | "register" | "forgot" | "dashboard" | "2fa" | "logout";
type RouteMeta = { title: string };

const routes: Record<RouteKey, RouteMeta> = {
    default: { title: "Authenticate" },
    home: { title: "Home" },
    login: { title: "Login" },
    register: { title: "Register" },
    forgot: { title: "Forgot Password" },
    dashboard: { title: "Dashboard" },
    "2fa": { title: "Two-Factor Authentication" },
    logout: { title: "Logout" },
};

export const copy = {
    error: { ...ERROR_COPY },
    trace_id: "Trace ID",

    routes,

    home_signed_in_as: "Signed in as",
    home_not_signed_in: "Not signed in",
    home_debug: "Debug",
    home_loading: "Loading...",

    register_title: "Welcome to the app",
    register_description: "Sign in with your email",
    login_title: "Welcome to the app",
    login_description: "Sign in with your email",

    register: "Register",
    register_prompt: "Don't have an account?",
    login_prompt: "Already have an account?",
    login: "Login",
    change_prompt: "Forgot password?",
    code_resend: "Resend code",
    code_return: "Back to",
    logo: "A",
    verify_email_prompt: "Enter the code that was sent to your email.",

    input_username: "Username",
    input_email: "Email",
    input_email_or_username: "Email or username",
    input_password: "Password",
    input_code: "Code",
    input_repeat: "Repeat password",
    button_continue: "Continue",
    button_skip: "Skip",
    button_verify: "Verify",

    otp_prompt: "Enter the code that was sent to your email.",
    otp_verified: "Email verified.",

    totp_show_qr: "Show QR Code",
    totp_prompt: "Use your preferred 2FA app to save your secret key.",
    totp_verified: "TOTP Verified.",
    totp_manual_secret: "Secret:",
    totp_manual_alg: "Algorithm:",
    totp_manual_period: "Period:",
    totp_manual_period_seconds: "seconds",
    totp_manual_digits: "Digits:",
    totp_open_app: "Open in authenticator app",
    totp_tab_link: "Link",
    totp_tab_qr: "QR",
    totp_tab_manual: "Manual",

    forgot_email_prompt: "Enter your email to reset your password.",
    forgot_code_prompt: "Enter the code sent to your email.",

    twofa_prompt_email: "Enter the code sent to your email",
    twofa_prompt_totp: "Enter the code shown in your authenticator app (TOTP).",
    twofa_resent_email: "Verification code resent to your email",
    twofa_switch_to_totp: "Use authenticator app instead",
    twofa_switch_to_email: "Use email verification instead",

    dashboard_title: "Account Settings",
    dashboard_password_changed: "Password changed successfully",
    dashboard_unknown_ip: "Unknown IP address",

    dashboard_email_heading: "Email",
    dashboard_email_verified_badge: "Verified",
    dashboard_email_unverified_badge: "Unverified",
    dashboard_email_change: "Change Email",
    dashboard_email_new_placeholder: "New email address",
    dashboard_email_verification_sent: "Email verification sent.",
    dashboard_email_unverified_prompt: "Email unverified.",
    dashboard_email_resend_verification: "Resend Email Verification",

    dashboard_password_heading: "Password",
    dashboard_password_repeat_password: "Repeat password",
    dashboard_password_repeat_password_placeholder: "Repeat password",
    dashboard_password_current_label: "Current Password",
    dashboard_password_current_placeholder: "Current password",
    dashboard_password_new_label: "New Password",
    dashboard_password_new_placeholder: "New password",
    dashboard_password_repeat_label: "Repeat New Password",
    dashboard_password_repeat_new_placeholder: "Repeat new password",
    dashboard_password_change: "Change Password",
    dashboard_password_set: "Set Password",
    dashboard_password_set_description: "Set a password to sign in directly.",

    dashboard_2fa_heading: "Two-Factor Authentication",
    dashboard_2fa_description: "Use an authenticator app (TOTP) for two factor authentication.",
    dashboard_2fa_enable: "Enable 2FA",
    dashboard_2fa_enabled_badge: "Enabled",
    dashboard_2fa_disabled_badge: "Disabled",
    dashboard_2fa_setup_prompt: "Verify using your authenticator app to complete setup.",
    dashboard_2fa_active: "Two-factor authentication is active.",
    dashboard_2fa_success: "Success!",
    dashboard_2fa_show_qr: "Show QR Code",
    dashboard_2fa_new_backup_codes: "New Backup Codes",
    dashboard_2fa_disable: "Disable 2FA",
    dashboard_2fa_optional_verify: "2FA is enabled, meaning no further action is necessary. Use the box below to test.",
    dashboard_2fa_verify_prompt: "Verify with a code from your app.",
    dashboard_2fa_code_placeholder: "6-digit code",
    dashboard_2fa_verify_button: "Verify Code",
    dashboard_2fa_open_totp_link: "Click to open in authenticator app.",

    dashboard_backup_codes_title: "Backup Codes",
    dashboard_backup_codes_copied: "Copied",
    dashboard_backup_codes_copy_all: "Copy All",
    dashboard_backup_codes_save: "Save these somewhere safe. Each code works once.",

    dashboard_linked_accounts_heading: "Linked Accounts",
    dashboard_linked_accounts_linked: "Linked",
    dashboard_linked_accounts_unlinked: "Not set",
    dashboard_linked_accounts_unlink: "Unlink",
    dashboard_linked_accounts_link: "Link",
    dashboard_linked_accounts_credential: "Email & Password",

    dashboard_sessions_heading: "Sessions",
    dashboard_session_current: "Current",
    dashboard_session_revoke: "Revoke",
    dashboard_session_revoke_other_sessions: "Revoke Other Sessions",
    dashboard_sessions_empty: "No active sessions",

    dashboard_delete_account_heading: "Danger Zone",
    dashboard_delete_account_button: "Delete Account",
    delete_confirm_button: "I'm sure. Delete my account",
    delete_title: "Delete Account",
    delete_section_header_password_only: "Enter your password to verify deleting your account.",
    delete_section_header: "Enter your password and 2FA to verify deleting your account.",
    delete_section_header_2fa_only: "Enter your 2FA code to verify deleting your account.",
    delete_section_header_confirm: "Are you sure you want to delete your account?",
    delete_section_2fa_totp: "Authenticator App (TOTP) Passcode",
    delete_section_2fa_email: "Email OTP",
    delete_go_back: "Back to safety",
    delete_success_header: "Your account has been successfully deleted.",

    email_otp_subject: "One time passcode",
    email_2fa_subject: "One time passcode",
    email_verification_subject: "Email verification",
    email_otp_body: "Your one-time login code for",
    email_otp_expiry: "This code expires in 15 minutes. Do not share it with anyone.",
    email_2fa_body: "Your two-factor authentication code for",
    email_2fa_expiry: "This code expires shortly. Do not share it with anyone.",
    email_verify_body: "Click the link below to verify the email address",
    email_footer_prefix:
        "If you did not initiate this request, you can safely ignore this email. If you believe your account has been compromised,",

    email_change_subject: "Change email address",
    email_change_body: "Click the link below to confirm changing your email address.",
    email_change_from: "From",
    email_change_to: "to",

    email_footer_reset: "reset your password",
    email_footer_middle: "or go to your",
    email_footer_dashboard: "dashboard",
    email_footer_suffix: "to review your account.",

    error_default: "An unexpected error occurred.",
    go_home: "Go home",
    go_back: "Back",
};

export type Copy = typeof copy;
